### ISSUE TITLE
What is the UX at the beginning oof Section 5?

### ISSUE THREAD

**Issue by adriatic** [lazarnikolov94/egghead-getting-started-with-chakra-ui#2]
I do not believe you introduced this rendering:

<p align="center">
  <img width="460" src="https://user-images.githubusercontent.com/2712405/154164602-857aee37-fc7c-43e5-aad1-10e0f354a3d4.png" />
<br>
<b>Image 1</b>
</p>

**Comment by nikolovlazar** [comment]
That's the Device Toolbar. If you can see at the bottom left of the screenshot, there's an "arrow in a box" icon which is for targeting elements, and then next to it there's a little "devices" icon that's highlighted in blue. That's the toggle device toolbar button.

**Comment by adriatic** [comment]
Thank you @nikolovlazar for this explanation. I am amazed that I was not aware of this feature, showing that I was not interested in responsive design.

**Comment by nikolovlazar** [comment]
That's fine! There are tons of tools out there, and new ones are getting created every day.
